- name: Auditoría de acceso a datos sensibles
  hosts: servidores_clinicos
  tasks:
    - name: Regla para monitorear acceso a la base de datos
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: "-w /var/lib/mysql/clinica_db -p rwa -k acceso_a_bd"
        state: present

    - name: Regla para detectar ejecución de herramientas de penetración
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: "-w /usr/bin/nmap -p x -k uso_herramientas_red"
        state: present
      notify: Recargar Auditd

  handlers:
    - name: Recargar Auditd
      shell: "augenrules --load"
