- name: Configuración de auditoría avanzada
  hosts: servidores_clinicos
  tasks:
    - name: Instalar Auditd
      package:
        name: auditd
        state: present

    - name: Configurar reglas de auditoría para archivos sensibles
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: "-w /etc/shadow -p wa -k credenciales_cambio"
        state: present

    - name: Monitorear acceso a carpetas
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: "-w /var/lib/dicom_data -p rwa -k hospital-san-lucas"
        state: present
      notify: Reiniciar Auditd

  handlers:
    - name: Reiniciar Auditd
      service:
        name: auditd
        state: restarted
        use: service # Auditd requiere gestión directa

