- name: Centralización de eventos y registros
  hosts: todos_los_servidores
  become: yes
  tasks:
    - name: Instalar Filebeat
      package:
        name: filebeat
        state: present

    - name: Habilitar módulos de seguridad en Filebeat
      command: "filebeat modules enable system auditd suricata"

    - name: Configurar salida hacia el servidor central del hospital
      copy:
        dest: /etc/filebeat/filebeat.yml
        content: |
          filebeat.inputs:
          - type: log
            paths:
              - /var/log/clamav/clamav.log
          output.elasticsearch:
            hosts: ["https://siem-central.sanlucas.local:9200"]
            username: "beats_user"
            password: "seguridad_password"
      notify: Reiniciar Filebeat

  handlers:
    - name: Reiniciar Filebeat
      service:
        name: filebeat
        state: restarted
