- name: Endurecimiento del hipervisor KVM
  hosts: hipervisores_san_lucas
  become: yes
  tasks:
    - name: Instalar componentes de virtualización críticos
      package:
        name: [qemu-kvm, libvirt-daemon-system, virtinst, bridge-utils]
        state: present

    - name: Asegurar que IOMMU esté activo (Protección de memoria a nivel hardware)
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash amd_iommu=on"' # Cambiar a intel_iommu=on si es procesador Intel
      notify: Actualizar GRUB

    - name: Restringir acceso al socket de libvirt
      copy:
        dest: /etc/libvirt/libvirtd.conf
        content: |
          unix_sock_group = "libvirt"
          unix_sock_rw_perms = "0770"
          auth_unix_rw = "polkit"
      notify: Reiniciar Libvirt
