[hipervisores_kvm]
hp-srv-kvm-01 ansible_host=10.0.1.10
hp-srv-kvm-02 ansible_host=10.0.1.11

[servidores_clinicos]
srv-pacs-01 ansible_host=10.0.2.10
srv-lab-01   ansible_host=10.0.2.20

[servidores_correo]
srv-mail-admin ansible_host=10.0.3.5

[servidores_administrativos]
srv-contabilidad ansible_host=10.0.4.10
srv-recursos     ansible_host=10.0.4.11

[all:vars]
ansible_user=admin_seguro
ansible_ssh_private_key_file=~/.ssh/id_rsa_hospital
