- name: Aleatorización de MAC
  hosts: #
  become: yes
  tasks:
    - name: Configuración de NetworkManager
      copy:
        dest: /etc/NetworkManager/conf.d/00-mac-randomization.conf
        content: |
          [device]
          wifi.scan-rand-mac-address=yes

          [connection]
          # Aleatorizar MAC durante el escaneo y la conexión
          wifi.cloned-mac-address=random
          ethernet.cloned-mac-address=random
      notify: Reiniciar NetworkManager

  handlers:
    - name: Reiniciar NetworkManager
      systemd:
        name: NetworkManager
        state: restarted
