- Configuración de Fail2Ban
    - name: Instalación y configuración
      apt:
        name: fail2ban
        state: present

    - name: Configurar protección para SSH en Fail2Ban
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [sshd]
          enabled = true
          port = ssh
          filter = sshd
          logpath = /var/log/auth.log
          maxretry = 3
          bantime = 1h
