- name: Implementación de Suricata
  hosts: servidores_clinicos
  become: yes
  vars:
    interfaz_red: "eth0" # Cambiar según el servidor
  tasks:
    - name: Instalar Suricata y utilidades
      apt:
        name: 
          - suricata
          - suricata-update
        state: present

    - name: Configurar interfaz de escucha en suricata.yaml
      lineinfile:
        path: /etc/suricata/suricata.yaml
        regexp: 'interface: eth0'
        line: "    interface: {{ interfaz_red }}"

    - name: Actualizar base de datos de reglas
      command: suricata-update
      register: update_result
      changed_when: "'No changes' not in update_result.stdout"

    - name: Habilitar modo IPS (Prevención) en el arranque
      systemd:
        name: suricata
        enabled: yes
        state: started

    - name: Configurar log rotativo para evitar saturación de disco
      copy:
        dest: /etc/logrotate.d/suricata
        content: |
          /var/log/suricata/*.log {
              weekly
              rotate 4
              compress
              missingok
              notifempty
          }
