- name: Endurecimiento de usuarios
  hosts: servidores_clinicos
  tasks:
    - name: Configurar caducidad de contraseñas (90 días)
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   90'

    - name: Deshabilitar cuentas de usuario inactivas
      command: useradd -D -f 30

    - name: Asegurar que sudo requiera contraseña siempre
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL:ALL) ALL'
        validate: '/usr/sbin/visudo -cf %s'
